version: '3.6'
networks:
  car-storage-net:
services:
  car-storage:
    image: dsniatecki/car-storage:0.3.0-java
    container_name: car-storage
    environment:
      GUARD_CERT_URI: "http:// <<GUARD-HOST>> /realms/ <<GUARD-REALM>> /protocol/openid-connect/certs"
      DB_HOST: car-storage-db
      DB_NAME: car-storage
      DB_USER: car-storage
      DB_PASSWORD: car-storage
    # DEVELOPMENT_MODE: "true"
    # APP_LOGGING_LEVEL: DEBUG
    ports:
      - "8080:8080"
    networks:
      - car-storage-net
    depends_on:
      - car-storage-db
  car-storage-db:
    image: postgres:14-alpine
    container_name: car-storage-db
    environment:
      POSTGRES_USER: car-storage
      POSTGRES_PASSWORD: car-storage
      POSTGRES_DB: car-storage
    ports:
      - "5432:5432"
    networks:
      - car-storage-net
  alert-manager:
    image: prom/alertmanager:v0.23.0
    container_name: alert-manager
    command: --config.file=/config/alertmanager.yml --log.level=info
    volumes:
      - ./utils/alertmanager/alertmanager.yml:/config/alertmanager.yml
    ports:
      - '11193:9093'
    networks:
      - car-storage-net
    depends_on:
      - prometheus
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: '/var/lib/grafana/dashboards/car_storage_dashboard.json'
    volumes:
      - ./utils/grafana/provisioning:/etc/grafana/provisioning
      - ./utils/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - '11000:3000'
    networks:
      - car-storage-net
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.33.3
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=info
    volumes:
      - ./utils/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./utils/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - '11190:9090'
    networks:
      - car-storage-net
  smtp-server:
    image: mailhog/mailhog:v1.0.1
    container_name: smtp-server
    ports:
      - '11025:1025'
      - '11005:8025'
    networks:
      - car-storage-net