global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: prometheus
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          service: 'prometheus'
  - job_name: car-storage-observability
    honor_labels: true
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'car-storage:8080' ]
        labels:
          service: 'car-storage'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alert-manager:9093' ]
